# Archdo baseline — captured 2026-05-05 14:41
# 174 fingerprints (187 original diagnostics)
#
# Each line is: rule_id|file|identifier
# Commit this file to track which violations are accepted as existing.
# Fingerprints are line-number independent — formatting changes won't churn them.

1.13|lib/search_tantivy/ecto.ex|SearchTantivy.Ecto
1.23|lib|SearchTantivy.Native
1.26|(compiled)|Phoenix.Router
1.26|(compiled)|SearchTantivy.Aggregation
1.26|(compiled)|SearchTantivy.Call
1.26|(compiled)|SearchTantivy.Document
1.26|(compiled)|SearchTantivy.Ecto
1.26|(compiled)|SearchTantivy.Index
1.26|(compiled)|SearchTantivy.Query
1.26|(compiled)|SearchTantivy.Schema
1.26|(compiled)|SearchTantivy.Searcher
1.26|(compiled)|SearchTantivy.Snippet
1.26|(compiled)|SearchTantivy.Tokenizer
1.26|(compiled)|SearchTantivy.Value
1.6|lib/search_tantivy/index.ex|SearchTantivy.Index
1.7|lib/search_tantivy/ecto.ex|SearchTantivy.Index.add_documents/2
11.4|lib/search_tantivy/native.ex|SearchTantivy.Native
4.10|lib/search_tantivy/native.ex|SearchTantivy.Native
4.14|lib/search_tantivy/native.ex|SearchTantivy.Native
4.19|lib/search_tantivy/native.ex|SearchTantivy.Native
4.1|lib/search_tantivy/native.ex|SearchTantivy.Native
4.1|lib/search_tantivy/native/index.ex|SearchTantivy.Native.Index
4.1|lib/search_tantivy/native/query.ex|SearchTantivy.Native.Query
4.22|lib|SearchTantivy.Aggregation
4.22|lib|SearchTantivy.Document
4.22|lib|SearchTantivy.Ecto
4.22|lib|SearchTantivy.Index
4.22|lib|SearchTantivy.Query
4.22|lib|SearchTantivy.Schema
4.22|lib|SearchTantivy.Searcher
4.22|lib|SearchTantivy.Tokenizer
4.23|lib|SearchTantivy.Aggregation
4.23|lib|SearchTantivy.Document
4.23|lib|SearchTantivy.Index
4.23|lib|SearchTantivy.Searcher
4.23|lib|SearchTantivy.Tokenizer
4.26|lib|SearchTantivy.Application
4.26|lib|SearchTantivy.Document
4.26|lib|SearchTantivy.Index
4.26|lib|SearchTantivy.Schema
4.8|project|742cf41
5.6|lib/search_tantivy/application.ex|3fa54f0
5.6|lib/search_tantivy/application.ex|623ac5
5.6|lib/search_tantivy/index_supervisor.ex|1dfa209
6.24|lib|SearchTantivy.Aggregation.aggregate/2
6.24|lib|SearchTantivy.Aggregation.avg/1
6.24|lib|SearchTantivy.Aggregation.count/1
6.24|lib|SearchTantivy.Aggregation.date_histogram/2
6.24|lib|SearchTantivy.Aggregation.date_histogram/3
6.24|lib|SearchTantivy.Aggregation.histogram/2
6.24|lib|SearchTantivy.Aggregation.histogram/3
6.24|lib|SearchTantivy.Aggregation.max/1
6.24|lib|SearchTantivy.Aggregation.min/1
6.24|lib|SearchTantivy.Aggregation.percentiles/1
6.24|lib|SearchTantivy.Aggregation.percentiles/2
6.24|lib|SearchTantivy.Aggregation.range/2
6.24|lib|SearchTantivy.Aggregation.range/3
6.24|lib|SearchTantivy.Aggregation.search/3
6.24|lib|SearchTantivy.Aggregation.stats/1
6.24|lib|SearchTantivy.Aggregation.sum/1
6.24|lib|SearchTantivy.Aggregation.terms/1
6.24|lib|SearchTantivy.Aggregation.terms/2
6.24|lib|SearchTantivy.Document.new/2
6.24|lib|SearchTantivy.Ecto
6.24|lib|SearchTantivy.Ecto.build_schema/1
6.24|lib|SearchTantivy.Ecto.delete_one/3
6.24|lib|SearchTantivy.Ecto.index_all/3
6.24|lib|SearchTantivy.Ecto.index_one/3
6.24|lib|SearchTantivy.Ecto.to_document/2
6.24|lib|SearchTantivy.Ecto.to_documents/2
6.24|lib|SearchTantivy.Index.add_and_commit/2
6.24|lib|SearchTantivy.Index.add_and_commit/3
6.24|lib|SearchTantivy.Index.add_documents/3
6.24|lib|SearchTantivy.Index.close/1
6.24|lib|SearchTantivy.Index.create/2
6.24|lib|SearchTantivy.Index.schema_ref/1
6.24|lib|SearchTantivy.Native.rustler_init/0
6.24|lib|SearchTantivy.Query.boost/2
6.24|lib|SearchTantivy.Query.exists/2
6.24|lib|SearchTantivy.Query.fuzzy_term/3
6.24|lib|SearchTantivy.Query.fuzzy_term/4
6.24|lib|SearchTantivy.Query.parse/2
6.24|lib|SearchTantivy.Query.phrase/3
6.24|lib|SearchTantivy.Query.phrase_prefix/3
6.24|lib|SearchTantivy.Query.regex/3
6.24|lib|SearchTantivy.Query.term_query/3
6.24|lib|SearchTantivy.Schema
6.24|lib|SearchTantivy.Schema.field_names/1
6.24|lib|SearchTantivy.Schema.field_type/2
6.24|lib|SearchTantivy.Searcher.search/2
6.24|lib|SearchTantivy.Tokenizer.register/2
6.24|lib|SearchTantivy.Value
6.24|lib|SearchTantivy.Value.to_string_value/1
6.24|lib|SearchTantivy.aggregate/2
6.24|lib|SearchTantivy.aggregate/3
6.24|lib|SearchTantivy.create_index/2
6.24|lib|SearchTantivy.create_index/3
6.24|lib|SearchTantivy.open_index/2
6.24|lib|SearchTantivy.search/2
6.24|lib|SearchTantivy.search/3
6.25|lib|SearchTantivy.Aggregation.aggregate/3
6.25|lib|SearchTantivy.Call.safe_call/3
6.25|lib|SearchTantivy.Index.add_documents/2
6.25|lib|SearchTantivy.Index.commit/1
6.25|lib|SearchTantivy.Index.create/3
6.25|lib|SearchTantivy.Index.delete_documents/3
6.25|lib|SearchTantivy.Index.open/2
6.25|lib|SearchTantivy.Index.reader/1
6.25|lib|SearchTantivy.IndexSupervisor.start_index/1
6.25|lib|SearchTantivy.Native.document_create/2
6.25|lib|SearchTantivy.Native.query_boost/2
6.25|lib|SearchTantivy.Native.query_exists/2
6.25|lib|SearchTantivy.Native.query_fuzzy_term/5
6.25|lib|SearchTantivy.Native.query_phrase/3
6.25|lib|SearchTantivy.Native.query_phrase_prefix/3
6.25|lib|SearchTantivy.Native.query_regex/3
6.25|lib|SearchTantivy.Native.query_term/3
6.25|lib|SearchTantivy.Native.schema_build/1
6.25|lib|SearchTantivy.Native.schema_field_exists/2
6.25|lib|SearchTantivy.Native.schema_get_field_names/1
6.25|lib|SearchTantivy.Native.schema_get_field_type/2
6.25|lib|SearchTantivy.Native.search_with_aggs/3
6.25|lib|SearchTantivy.Native.tokenizer_register/2
6.25|lib|SearchTantivy.Schema
6.25|lib|SearchTantivy.Schema.build/1
6.25|lib|SearchTantivy.Searcher.search/3
6.26|lib|SearchTantivy.Aggregation
7.14|lib/search_tantivy/aggregation.ex|SearchTantivy.Aggregation
7.14|lib/search_tantivy/document.ex|SearchTantivy.Document
7.14|lib/search_tantivy/ecto.ex|SearchTantivy.Ecto
7.14|lib/search_tantivy/index.ex|SearchTantivy.Index
7.14|lib/search_tantivy/index_registry.ex|SearchTantivy.IndexRegistry
7.14|lib/search_tantivy/native.ex|SearchTantivy.Native
7.14|lib/search_tantivy/query.ex|SearchTantivy.Query
7.14|lib/search_tantivy/schema.ex|SearchTantivy.Schema
7.14|lib/search_tantivy/searcher.ex|SearchTantivy.Searcher
7.14|lib/search_tantivy/tokenizer.ex|SearchTantivy.Tokenizer
7.1|lib/search_tantivy/index_registry.ex|583cc43
7.1|lib/search_tantivy/index_supervisor.ex|6fc235b
7.1|lib/search_tantivy/native.ex|4d18c74
7.1|lib/search_tantivy/native/index.ex|4af1dc7
7.1|lib/search_tantivy/native/query.ex|51eda98
7.1|lib/search_tantivy/native/schema.ex|6f7e3a3
7.1|lib/search_tantivy/native/search.ex|c143ec
7.1|lib/search_tantivy/native/writer.ex|600bce7
7.1|lib/search_tantivy/searcher.ex|7250ef9
7.1|lib/search_tantivy/snippet.ex|4208a24
7.25|lib/search_tantivy/index_registry.ex|SearchTantivy.IndexRegistry
7.25|lib/search_tantivy/native.ex|SearchTantivy.Native
7.25|lib/search_tantivy/native/index.ex|SearchTantivy.Native.Index
7.25|lib/search_tantivy/native/query.ex|SearchTantivy.Native.Query
7.25|lib/search_tantivy/native/schema.ex|SearchTantivy.Native.Schema
7.25|lib/search_tantivy/native/search.ex|SearchTantivy.Native.Search
7.25|lib/search_tantivy/native/writer.ex|SearchTantivy.Native.Writer
7.25|lib/search_tantivy/searcher.ex|SearchTantivy.Searcher
7.25|lib/search_tantivy/snippet.ex|SearchTantivy.Snippet
CE-11|lib/search_tantivy/application.ex|SearchTantivy.Application
CE-12|lib/search_tantivy/application.ex|SearchTantivy.Application
CE-12|lib/search_tantivy/index.ex|SearchTantivy.Index
CE-12|lib/search_tantivy/index_supervisor.ex|SearchTantivy.IndexSupervisor
CE-21|lib/search_tantivy/index.ex|7ac0824
CE-28|lib/search_tantivy/searcher.ex|search/3
CE-28|lib/search_tantivy/value.ex|to_string_value/1
CE-30|lib/search_tantivy.ex|socket/3
CE-30|lib/search_tantivy/document.ex|SearchTantivy.Document
CE-30|lib/search_tantivy/ecto.ex|SearchTantivy.Ecto
CE-30|lib/search_tantivy/native/index.ex|SearchTantivy.Native.Index
CE-30|lib/search_tantivy/native/query.ex|SearchTantivy.Native.Query
CE-30|lib/search_tantivy/native/schema.ex|SearchTantivy.Native.Schema
CE-30|lib/search_tantivy/native/search.ex|SearchTantivy.Native.Search
CE-30|lib/search_tantivy/native/writer.ex|SearchTantivy.Native.Writer
CE-30|lib/search_tantivy/snippet.ex|SearchTantivy.Snippet
CE-30|lib/search_tantivy/tokenizer.ex|SearchTantivy.Tokenizer
CE-30|lib/search_tantivy/value.ex|SearchTantivy.Value
